services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chutes_audit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  auditor:
    build:
      context: .
      no_cache: true
    working_dir: /audit
    command: poetry run python audit.py
    volumes:
      - ${PWD}/audit.py:/audit/audit.py
      - ${PWD}/config:/audit/config
      - hfhub:/root/.cache/huggingface
      - ./reports:/reports
    environment:
      - POSTGRESQL=postgresql+asyncpg://user:password@postgres:5432/chutes_audit
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:
  hfhub:
